apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
  labels:
    app: device-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      containers:
        - name: device-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/prod/device-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4018
            - containerPort: 5018
          envFrom:
            - secretRef:
                name: device-service-secret
